# Generated by Django 5.1.6 on 2025-02-22 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_movie_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.TextField(max_length=3, null=True),
        ),
    ]
